/// Physical keyboard key code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum KeyboardKey {
    Unidentified,
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}

impl KeyboardKey {
    pub fn from_web_code(code: &str) -> Self {
        match code {
            "Unidentified" => Self::Unidentified,
            "Backquote" => Self::Backquote,
            "Backslash" => Self::Backslash,
            "BracketLeft" => Self::BracketLeft,
            "BracketRight" => Self::BracketRight,
            "Comma" => Self::Comma,
            "Digit0" => Self::Digit0,
            "Digit1" => Self::Digit1,
            "Digit2" => Self::Digit2,
            "Digit3" => Self::Digit3,
            "Digit4" => Self::Digit4,
            "Digit5" => Self::Digit5,
            "Digit6" => Self::Digit6,
            "Digit7" => Self::Digit7,
            "Digit8" => Self::Digit8,
            "Digit9" => Self::Digit9,
            "Equal" => Self::Equal,
            "IntlBackslash" => Self::IntlBackslash,
            "IntlRo" => Self::IntlRo,
            "IntlYen" => Self::IntlYen,
            "KeyA" => Self::KeyA,
            "KeyB" => Self::KeyB,
            "KeyC" => Self::KeyC,
            "KeyD" => Self::KeyD,
            "KeyE" => Self::KeyE,
            "KeyF" => Self::KeyF,
            "KeyG" => Self::KeyG,
            "KeyH" => Self::KeyH,
            "KeyI" => Self::KeyI,
            "KeyJ" => Self::KeyJ,
            "KeyK" => Self::KeyK,
            "KeyL" => Self::KeyL,
            "KeyM" => Self::KeyM,
            "KeyN" => Self::KeyN,
            "KeyO" => Self::KeyO,
            "KeyP" => Self::KeyP,
            "KeyQ" => Self::KeyQ,
            "KeyR" => Self::KeyR,
            "KeyS" => Self::KeyS,
            "KeyT" => Self::KeyT,
            "KeyU" => Self::KeyU,
            "KeyV" => Self::KeyV,
            "KeyW" => Self::KeyW,
            "KeyX" => Self::KeyX,
            "KeyY" => Self::KeyY,
            "KeyZ" => Self::KeyZ,
            "Minus" => Self::Minus,
            "Period" => Self::Period,
            "Quote" => Self::Quote,
            "Semicolon" => Self::Semicolon,
            "Slash" => Self::Slash,
            "AltLeft" => Self::AltLeft,
            "AltRight" => Self::AltRight,
            "Backspace" => Self::Backspace,
            "CapsLock" => Self::CapsLock,
            "ContextMenu" => Self::ContextMenu,
            "ControlLeft" => Self::ControlLeft,
            "ControlRight" => Self::ControlRight,
            "Enter" => Self::Enter,
            "MetaLeft" | "OSLeft" | "SuperLeft" => Self::SuperLeft,
            "MetaRight" | "OSRight" | "SuperRight" => Self::SuperRight,
            "ShiftLeft" => Self::ShiftLeft,
            "ShiftRight" => Self::ShiftRight,
            "Space" => Self::Space,
            "Tab" => Self::Tab,
            "Convert" => Self::Convert,
            "KanaMode" => Self::KanaMode,
            "Lang1" => Self::Lang1,
            "Lang2" => Self::Lang2,
            "Lang3" => Self::Lang3,
            "Lang4" => Self::Lang4,
            "Lang5" => Self::Lang5,
            "NonConvert" => Self::NonConvert,
            "Delete" => Self::Delete,
            "End" => Self::End,
            "Help" => Self::Help,
            "Home" => Self::Home,
            "Insert" => Self::Insert,
            "PageDown" => Self::PageDown,
            "PageUp" => Self::PageUp,
            "ArrowDown" => Self::ArrowDown,
            "ArrowLeft" => Self::ArrowLeft,
            "ArrowRight" => Self::ArrowRight,
            "ArrowUp" => Self::ArrowUp,
            "NumLock" => Self::NumLock,
            "Numpad0" => Self::Numpad0,
            "Numpad1" => Self::Numpad1,
            "Numpad2" => Self::Numpad2,
            "Numpad3" => Self::Numpad3,
            "Numpad4" => Self::Numpad4,
            "Numpad5" => Self::Numpad5,
            "Numpad6" => Self::Numpad6,
            "Numpad7" => Self::Numpad7,
            "Numpad8" => Self::Numpad8,
            "Numpad9" => Self::Numpad9,
            "NumpadAdd" => Self::NumpadAdd,
            "NumpadBackspace" => Self::NumpadBackspace,
            "NumpadClear" => Self::NumpadClear,
            "NumpadClearEntry" => Self::NumpadClearEntry,
            "NumpadComma" => Self::NumpadComma,
            "NumpadDecimal" => Self::NumpadDecimal,
            "NumpadDivide" => Self::NumpadDivide,
            "NumpadEnter" => Self::NumpadEnter,
            "NumpadEqual" => Self::NumpadEqual,
            "NumpadHash" => Self::NumpadHash,
            "NumpadMemoryAdd" => Self::NumpadMemoryAdd,
            "NumpadMemoryClear" => Self::NumpadMemoryClear,
            "NumpadMemoryRecall" => Self::NumpadMemoryRecall,
            "NumpadMemoryStore" => Self::NumpadMemoryStore,
            "NumpadMemorySubtract" => Self::NumpadMemorySubtract,
            "NumpadMultiply" => Self::NumpadMultiply,
            "NumpadParenLeft" => Self::NumpadParenLeft,
            "NumpadParenRight" => Self::NumpadParenRight,
            "NumpadStar" => Self::NumpadStar,
            "NumpadSubtract" => Self::NumpadSubtract,
            "Escape" => Self::Escape,
            "Fn" => Self::Fn,
            "FnLock" => Self::FnLock,
            "PrintScreen" => Self::PrintScreen,
            "ScrollLock" => Self::ScrollLock,
            "Pause" => Self::Pause,
            "BrowserBack" => Self::BrowserBack,
            "BrowserFavorites" => Self::BrowserFavorites,
            "BrowserForward" => Self::BrowserForward,
            "BrowserHome" => Self::BrowserHome,
            "BrowserRefresh" => Self::BrowserRefresh,
            "BrowserSearch" => Self::BrowserSearch,
            "BrowserStop" => Self::BrowserStop,
            "Eject" => Self::Eject,
            "LaunchApp1" => Self::LaunchApp1,
            "LaunchApp2" => Self::LaunchApp2,
            "LaunchMail" => Self::LaunchMail,
            "MediaPlayPause" => Self::MediaPlayPause,
            "MediaSelect" => Self::MediaSelect,
            "MediaStop" => Self::MediaStop,
            "MediaTrackNext" => Self::MediaTrackNext,
            "MediaTrackPrevious" => Self::MediaTrackPrevious,
            "Power" => Self::Power,
            "Sleep" => Self::Sleep,
            "AudioVolumeDown" => Self::AudioVolumeDown,
            "AudioVolumeMute" => Self::AudioVolumeMute,
            "AudioVolumeUp" => Self::AudioVolumeUp,
            "WakeUp" => Self::WakeUp,
            "Meta" => Self::Meta,
            "Hyper" => Self::Hyper,
            "Turbo" => Self::Turbo,
            "Abort" => Self::Abort,
            "Resume" => Self::Resume,
            "Suspend" => Self::Suspend,
            "Again" => Self::Again,
            "Copy" => Self::Copy,
            "Cut" => Self::Cut,
            "Find" => Self::Find,
            "Open" => Self::Open,
            "Paste" => Self::Paste,
            "Props" => Self::Props,
            "Select" => Self::Select,
            "Undo" => Self::Undo,
            "Hiragana" => Self::Hiragana,
            "Katakana" => Self::Katakana,
            "F1" => Self::F1,
            "F2" => Self::F2,
            "F3" => Self::F3,
            "F4" => Self::F4,
            "F5" => Self::F5,
            "F6" => Self::F6,
            "F7" => Self::F7,
            "F8" => Self::F8,
            "F9" => Self::F9,
            "F10" => Self::F10,
            "F11" => Self::F11,
            "F12" => Self::F12,
            "F13" => Self::F13,
            "F14" => Self::F14,
            "F15" => Self::F15,
            "F16" => Self::F16,
            "F17" => Self::F17,
            "F18" => Self::F18,
            "F19" => Self::F19,
            "F20" => Self::F20,
            "F21" => Self::F21,
            "F22" => Self::F22,
            "F23" => Self::F23,
            "F24" => Self::F24,
            "F25" => Self::F25,
            "F26" => Self::F26,
            "F27" => Self::F27,
            "F28" => Self::F28,
            "F29" => Self::F29,
            "F30" => Self::F30,
            "F31" => Self::F31,
            "F32" => Self::F32,
            "F33" => Self::F33,
            "F34" => Self::F34,
            "F35" => Self::F35,
            _ => Self::Unidentified,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub(crate) struct KeyboardState {
    pub(crate) up: bool,
    pub(crate) down: bool,
    pub(crate) left: bool,
    pub(crate) right: bool,
}

impl KeyboardState {
    pub(crate) fn set(&mut self, key: KeyboardKey, pressed: bool) {
        match key {
            KeyboardKey::ArrowUp | KeyboardKey::KeyW => self.up = pressed,
            KeyboardKey::ArrowDown | KeyboardKey::KeyS => self.down = pressed,
            KeyboardKey::ArrowLeft | KeyboardKey::KeyA => self.left = pressed,
            KeyboardKey::ArrowRight | KeyboardKey::KeyD => self.right = pressed,
            _ => {}
        }
    }

    pub(crate) fn active(&self) -> bool {
        self.up || self.down || self.left || self.right
    }
}
