import { chromium } from "/home/nick/projects/rl-web/node_modules/playwright/index.mjs";
const BASE = "http://localhost:3001";
const OUT = "/home/nick/projects/pdx-tools/src/app/.impeccable/review";
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/api/login/steam-callback?returnTo=/users/200`, { waitUntil: "networkidle" });
await page.waitForTimeout(800);
await page.getByRole("switch").click();
await page.waitForTimeout(800);
console.log("status:", await page.locator("li span[aria-live]").innerText());
await page.screenshot({ path: `${OUT}/features-granted.png`, clip: { x: 200, y: 160, width: 1040, height: 220 } });
await page.getByRole("switch").click();
await page.waitForTimeout(800);
console.log("status:", await page.locator("li span[aria-live]").innerText());
await page.goto(`${BASE}/users/100`, { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.screenshot({ path: `${OUT}/desktop.png`, fullPage: true });
await page.getByRole("button", { name: "Copy link" }).first().click();
await page.waitForTimeout(300);
await page.screenshot({ path: `${OUT}/card-copied.png`, fullPage: true, clip: { x: 200, y: 900, width: 1040, height: 120 } });
await page.getByRole("button", { name: "Delete save" }).first().click();
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/desktop-delete.png` });
await browser.close();
