packages:
  - src/app
  - src/docs
  - src/map
  - src/pdx-map-playground
catalog:
  '@types/node': 22.18.0
  comlink: 4.4.2
  react-dom: 19.2.0
  react: 19.2.0
  typescript: 5.6.3
  vite: 6.4.1
  wrangler: 4.43.0
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - workerd
