packages:
  - src/app
  - src/docs
  - src/map
  - src/pdx-map-playground
catalog:
  '@types/node': 24.9.1
  comlink: 4.4.2
  react-dom: 19.2.7
  react: 19.2.7
  typescript: 6.0.3
  vite: 8.1.4
  wrangler: 4.107.0
allowBuilds:
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true
