packages:
  - src/app
  - src/docs
  - src/map
  - src/timelapse
  - src/pdx-map-playground
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
catalog:
  '@types/node': 24.9.1
  comlink: 4.4.2
  react-dom: 19.3.0
  react: 19.3.0
  typescript: 7.0.2
  vite: 8.3.0
  wrangler: 4.131.1
allowBuilds:
  '@sentry/cli': true
  '@tailwindcss/oxide': true
  core-js: false
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true
