packages:
  - src/app
  - src/desktop
  - src/docs
  - src/map
  - src/pdx-map-playground
catalog:
  '@types/node': 24.9.1
  comlink: 4.4.2
  react-dom: 19.2.3
  react: 19.2.3
  typescript: 5.9.3
  vite: 7.3.1
  wrangler: 4.61.1
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - workerd
