packages:
  - src/app
  - src/docs
  - src/map
  - src/pdx-map-playground
catalog:
  '@types/node': 22.18.0
  comlink: 4.4.2
  typescript: 5.6.3
  vite: 6.3.7
  wrangler: 3.92.0
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - workerd
