#!/usr/bin/env bash

set -euxo pipefail

#USAGE arg "<environment>" help="The target to build"

. dev/.env.app.$usage_environment

ssh pdx-tools-$usage_environment '/opt/pdx-tools/docker-compose.sh exec -T --user postgres db pg_dump --exclude-table=\*prisma\* --data-only' > db-$usage_environment.dump
ssh pdx-tools-$usage_environment '/opt/pdx-tools/docker-compose.sh exec -T --user postgres db psql --command "\COPY saves TO STDOUT CSV HEADER"' > db-$usage_environment-saves.csv

export RCLONE_CONFIG_PDX_ACCESS_KEY_ID="$S3_ACCESS_KEY"
export RCLONE_CONFIG_PDX_SECRET_ACCESS_KEY="$S3_SECRET_KEY"
export RCLONE_CONFIG_PDX_REGION="$S3_REGION"
export RCLONE_CONFIG_PDX_ENDPOINT="${S3_ENDPOINT/https:\/\//}"

rclone sync --no-gzip-encoding --backup-dir ./saves-archive "pdx:/$S3_BUCKET" ./saves
