services:
  db:
    extends:
      file: docker-compose.db.yml
      service: db

    # Need a separate dockerfile due to how volume mounts are resolved
    # in docker in docker scenarios
    build:
      dockerfile: postgres.dockerfile
      context: .
    ports:
      - "${DATABASE_PORT}:5432"
