# Used as an override for prod to make S3 self hosted
services:
  s3:
    image: minio/minio@sha256:c92f04149c93010eefc4e4581b18fb4b9ea46af8e9f658291c377388b7691828
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/bash -c "
      /usr/bin/mc config --insecure host add myminio $${SCHEME-http}://s3:9000 miniominio minio12minio;
      /usr/bin/mc mb --insecure --ignore-existing myminio/savefiles;
      exit 0;
      "
