export type VizModules =
  | "idea-group"
  | "monthly-income"
  | "nation-size"
  | "inflation"
  | "score"
  | "health"
  | "income-table"
  | "expense-table"
  | "total-expense-table"
  | "army-casualties"
  | "navy-casualties"
  | "wars"
  | "geographical-development"
  | "owned-development-states"
  | "provinces"
  | "dev-efficiency";
