[package]
name = "eu5-streaming"
version = "0.1.0"
edition = "2024"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
eu5app = { path = "../../src/eu5app", default-features = false, features = ["tsify", "zstd_rust"] }
eu5save = { git = "https://github.com/rakaly/jomini.git", default-features = false }
js-sys = "=0.3.95"
wasm-bindgen = "=0.2.118"
serde = { version = "1.0.228", features = ["derive"] }
tsify = { version = "0.5.8", default-features = false, features = ["js"] }
blake3 = { version = "=1.8.7", features = ["wasm32_simd"] }
arena-serde = { git = "https://github.com/rakaly/jomini.git" }
bumpalo = "3.20"
jomini = { version = "0.37.1", features = ["envelope"] }
[profile.release]
lto = "thin"
opt-level = 3
