[package]
name = "wasm-compress"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd_rust"]
zstd_c = ["dep:zstd"]
zstd_rust = ["dep:ruzstd"]

[dependencies]
flate2 = { default-features = false, features = ["zlib-rs"] , workspace = true }
js-sys = { workspace = true }
rawzip = { workspace = true }
ruzstd = { optional = true, workspace = true }
serde = { features = ["derive"] , workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
wasm-bindgen = { workspace = true }
zstd = { default-features = false, optional = true, workspace = true }
