[package]
name = "wasm-compress"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
flate2 = { default-features = false, features = ["zlib-rs"] , workspace = true }
rawzip = { workspace = true }
zstd = { default-features = false, workspace = true }
js-sys = { workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
serde = { features = ["derive"] , workspace = true }
