[package]
name = "wasm-compress"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd_rust"]
zstd_c = ["pdx-zstd/zstd_c"]
zstd_rust = ["pdx-zstd/zstd_rust"]
zstd_c_fat_lto = ["pdx-zstd/zstd_c_fat_lto"]

[dependencies]
flate2 = { default-features = false, features = ["zlib-rs"] , workspace = true }
js-sys = { workspace = true }
pdx-zstd = { workspace = true }
rawzip = { workspace = true }
serde = { features = ["derive"] , workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
wasm-bindgen = { workspace = true }
