#!/bin/sh

psql -c "CREATE ROLE db_backup WITH LOGIN PASSWORD '$DATABASE_BACKUP_PASSWORD'"
psql -c "ALTER DEFAULT PRIVILEGES 
FOR USER postgres
IN SCHEMA public
GRANT SELECT ON TABLES TO db_backup;"

psql -c "CREATE ROLE $DATABASE_APP_USER WITH LOGIN PASSWORD '$DATABASE_APP_USER_PASSWORD'"
psql -c "ALTER DEFAULT PRIVILEGES 
FOR USER postgres
IN SCHEMA public
GRANT SELECT,UPDATE,INSERT,DELETE ON TABLES TO $DATABASE_APP_USER;"
