[package]
name = "hoi4app"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
default = ["zstd_rust"]
game-install = ["dep:jomini", "dep:rawbmp"]
tsify = ["dep:tsify", "dep:wasm-bindgen"]
zstd_c = ["pdx-zstd/zstd_c"]
zstd_rust = ["pdx-zstd/zstd_rust"]

[dependencies]
bytemuck = { workspace = true }
hoi4save = { workspace = true }
jomini = { workspace = true, optional = true }
pdx-map = { workspace = true, default-features = false }
pdx-zstd = { workspace = true, default-features = false }
postcard = { workspace = true, features = ["use-std"] }
rawbmp = { workspace = true, optional = true }
rawzip = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
hoi4app = { path = ".", default-features = false, features = ["game-install", "zstd_rust"] }
