// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	PUPPETEER_URL: string;
	PUPPETEER_TOKEN: string;
	S3_BUCKET: string;
	S3_REGION: string;
	S3_ACCESS_KEY: string;
	S3_SECRET_KEY: string;
	S3_ENDPOINT: string;
	SENTRY_HOST: string;
	SENTRY_PROJECT_ID: string;
	PARSE_API_ENDPOINT: string;
	STEAM_API_KEY: string;
	STEAM_LOGIN_ADDRESS: string;
	SKAN_API_KEY: string;
	PDX_DB: Hyperdrive;
}
