#:schema node_modules/wrangler/config-schema.json
name = "pdx-tools-workers"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]
main = "./server.ts"

[assets]
directory = "./build/client"

[observability]
enabled = true
head_sampling_rate = 1

[version_metadata]
binding = "CF_VERSION_METADATA"

[[hyperdrive]]
binding = "PDX_DB"
id = "52bcc7b655d44776a6e42672fd11b388"
localConnectionString = "postgres://app_user:mercantilismbaby2@localhost:5432/postgres"

[env.test]

[[env.test.hyperdrive]]
binding = "PDX_DB"
id = "52bcc7b655d44776a6e42672fd11b388"
localConnectionString = "postgres://app_user:mercantilismbaby@localhost:5433/postgres"

[env.test.version_metadata]
binding = "CF_VERSION_METADATA"
