#:schema node_modules/wrangler/config-schema.json
name = "pdx-tools-workers"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]
main = "./server.ts"

[assets]
directory = "./build/client"

[observability]
enabled = true
head_sampling_rate = 1

[[hyperdrive]]
binding = "PDX_DB"
id = "52bcc7b655d44776a6e42672fd11b388"
localConnectionString = "postgres://user:password@localhost:5432/databasename"

[[durable_objects.bindings]]
name = "WEBSOCKET_LIVE_SERVER"
class_name = "LiveSessionWebsocketServer"
script_name = "./app/routes/api.users.$userId.live.ts"

[[migrations]]
tag = "v1"
new_classes = ["LiveSessionWebsocketServer"]

[env.test]

[[env.test.hyperdrive]]
binding = "PDX_DB"
id = "52bcc7b655d44776a6e42672fd11b388"
localConnectionString = "postgres://user:password@localhost:5432/databasename"
