[package]
name = "pdx-tools-api"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
applib = { workspace = true, default-features = false, features = ["zstd_c"] }
axum = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
eu5app = { workspace = true, default-features = false, features = ["zstd_c"] }
eu5save = { workspace = true, default-features = false }
jomini = { workspace = true, features = ["zstd_c"] }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
pdx-map = { workspace = true, features = ["render", "date-layer", "tracing"] }
pdx-screenshot = { workspace = true, features = ["eu4", "eu5"] }
pdx-zstd = { workspace = true, features = ["zstd_c"] }
schemas = { workspace = true, features = ["inline"] }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "signal", "sync"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[target.'cfg(target_env = "musl")'.dependencies]
mimalloc = { workspace = true }

[dev-dependencies]
pdx-assets = { workspace = true }
pdx-save-codec = { workspace = true, features = ["zstd_c"] }
