[package]
name = "wasm-vic3"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd/fat-lto"]

[dependencies]
jomini = { workspace = true }
schemas = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { features = ["derive"] , workspace = true }
vic3save = { workspace = true }
js-sys = { workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
zstd = { default-features = false , workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
dwarf-debug-info = true
