[package]
name = "wasm-vic3"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd/fat-lto"]

[dependencies]
jomini = {version = "0.28.0"}
schemas = { path = "../schemas" }
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = "0.5"
serde = { version = "1.0.195", features = ["derive"] }
vic3save = { path = "../vic3save" }
js-sys = "0.3"
tsify = { version = "0.4.5", default-features = false, features = ["js"] } 
zstd = { version = "0.13.0", default-features = false }


[package.metadata.wasm-pack.profile.release]
wasm-opt = false
