[package]
name = "wasm-vic3"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd_rust"]
zstd_c = ["pdx-zstd/zstd_c"]
zstd_c_fat_lto = ["pdx-zstd/zstd_c_fat_lto"]
zstd_rust = ["pdx-zstd/zstd_rust"]

[dependencies]
jomini = { workspace = true }
schemas = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { features = ["derive"] , workspace = true }
vic3save = { workspace = true }
js-sys = { workspace = true }
pdx-zstd = { workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
