[package]
name = "wasm-vic3"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["zstd_rust"]
zstd_c = ["dep:zstd"]
zstd_c_fat_lto = ["zstd_c", "zstd/fat-lto"]
zstd_rust = ["dep:ruzstd"]

[dependencies]
jomini = { workspace = true }
schemas = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { features = ["derive"] , workspace = true }
vic3save = { workspace = true }
js-sys = { workspace = true }
ruzstd = { optional = true, workspace = true }
tsify = { default-features = false, features = ["js"] , workspace = true }
zstd = { default-features = false, optional = true, workspace = true }
