[tools]
"docker-compose" = { version = "2.33.1" }
"just" = { version = "1.40.0" }
"node" = { version = "22.15.0" }
"npm:concurrently" = { version = "9.1.2" }
"npm:npm-check-updates" = { version = "17.1.18" }
"pnpm" = { version = "10.11.0" }
"rust" = { version = "1.87.0", targets = "wasm32-unknown-unknown,x86_64-unknown-linux-musl" }
"ubi:cargo-bins/cargo-binstall" = { version = "1.12.5" }
"ubi:google/flatbuffers" = { version = "25.2.10", matching = "clang", exe = "flatc" }
"ubi:jqlang/jq" = { version = "jq-1.7.1" }
"ubi:rustwasm/wasm-bindgen" = { version = "0.2.100", extract_all = "true" }
"ubi:WebAssembly/binaryen" = { version = "version_123", extract_all = "true", bin_path = "bin" }
"vfox:mise-plugins/vfox-clang" = { version = "18.1.6" }
