// This file has been generated by Specta. DO NOT EDIT.

export type ParseResult = ({ kind: "InvalidPatch" } & InvalidPatch) | ({ kind: "Parsed" } & ParsedFile)

export type SavePatch = { first: number; second: number; third: number; fourth: number }

/**
 * Describes the format of the save before decoding
 */
export type Encoding = "text" | "textzip" | "binzip" | "binary"

export type ParsedFile = { patch: SavePatch; encoding: Encoding; playthrough_id: string; game_difficulty: GameDifficulty; is_ironman: boolean; is_multiplayer: boolean; player_names: string[]; player_tag: string; player_tag_name: string; player_start_tag: string | null; player_start_tag_name: string | null; date: string; days: number; score_date: string; score_days: number; achievements: number[] | null; patch_shorthand: string; hash: string }

export type GameDifficulty = "VeryEasy" | "Easy" | "Normal" | "Hard" | "VeryHard"

export type InvalidPatch = { patch_shorthand: string }

